@startuml
title 管理员用例图
left to right direction
actor 管理员

rectangle 管理员端功能 {
  (登录系统)
  (学生管理)
  (教师管理)
  (学院/专业/班级管理)
  (课程与培养计划)
  (教学任务分配)
  (课表管理)
}

管理员 --> (登录系统)
管理员 --> (学生管理)
管理员 --> (教师管理)
管理员 --> (学院/专业/班级管理)
管理员 --> (课程与培养计划)
管理员 --> (教学任务分配)
管理员 --> (课表管理)
@enduml
