@startuml
title 学生用例图
left to right direction
actor 学生

rectangle 学生端功能 {
  (登录系统)
  (查看成绩)
  (下载课表)
  (选课)
  (修改密码)
  (打印成绩单)
}

学生 --> (登录系统)
学生 --> (查看成绩)
学生 --> (下载课表)
学生 --> (选课)
学生 --> (修改密码)
学生 --> (打印成绩单)
@enduml
