@startuml
title 教师流程图
start
:登录系统;
if (验证码与账号验证通过?) then (是)
  :进入教师工作台;
  :查看教学任务;
  if (录入成绩?) then (是)
    :输入课程与学生成绩;
    :提交成绩;
  endif
  if (下载课表/点名册?) then (是)
    :选择学期或班级;
    :下载文件;
  endif
  if (修改密码?) then (是)
    :输入新密码;
    :提交修改;
  endif
  :退出登录;
else (否)
  :提示错误;
endif
stop
@enduml
