@startuml
title 教师用例图
left to right direction
actor 教师

rectangle 教师端功能 {
  (登录系统)
  (查看教学任务)
  (录入成绩)
  (查询成绩)
  (下载课表)
  (导出点名册)
  (修改密码)
}

教师 --> (登录系统)
教师 --> (查看教学任务)
教师 --> (录入成绩)
教师 --> (查询成绩)
教师 --> (下载课表)
教师 --> (导出点名册)
教师 --> (修改密码)
@enduml
